repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace         # Removes trailing whitespace
    -   id: check-yaml                  # Validates YAML syntax
    -   id: check-added-large-files     # Prevents adding large files
