name: Basic Checks
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ develop ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Python Syntax Check
      run: |
        find . -name "*.py" -type f -exec python -m py_compile {} \;
